// Auto-generated by Makefile Wed Feb 01 21:03:45 2023

#define PACKAGE "mc"
#define PACKAGE_NAME "Midnight Commander WIN32"
#define VERSION "4.8.29"
#define VERSION_1 4
#define VERSION_2 8
#define VERSION_3 29
#define VERSION_4 228
#define BUILD_DATE "20230201"
#define BUILD_NUMBER "228"
#define BUILD_TOOLCHAIN ".owc19"
#define BUILD_TYPE "debug"
#define BUILD_TYPE_DEBUG 1
